### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by thatname** [andrejnau/FlyCube#20]
Hi, this library is very cool ! 
After using it, I have some suggestions:
* Make VKResource and MTLResource abstract, move implementation to image/buffer/sampler/accel subclasses. After change:
  * Resource subclasses cost less memory.
  * Most branching logic can be removed, because all methods of Resource are virtual.
* Add build targets for each underlying graphics API, then we can build dynamic libraries.
* Add CopyTextureToBuffer(), which is useful.
* Make debug layer optional. For now, debug layer is always enabled when debugger attached, which is slow.
* Add depth range parameter for SetViewport().
* Remove glm from acceleration structure dependency, user may prefer other math library.
* Required CMake version is too high(3.28), lower to 3.1x?
* Use CMake fetchContent instead of git submodules for external dependencies, which is more flexible.
I've forked the repo, trying to accomplish all the above. I'll open a pull request if helpful.

**Comment by andrejnau** [comment]
Hi! I'm glad you liked it. And thanks for pointing out some issues.

Yes, there are some functions missing and probably not just CopyTextureToBuffer or depth range. As well as some code need a bit refactoring.

> Add build targets for each underlying graphics API, then we can build dynamic libraries.

I will add target `FlyCube` that contains implementation for all graphics backends. Is this what you offer?

> Required CMake version is too high(3.28), lower to 3.1x?

3.28 was required to link with MoltenVK.xcframework. I ended up replacing the version with 3.22 in https://github.com/andrejnau/FlyCube/commit/bd18fbd1b8cffbe88b12fd42f07a93eea9d40374 . Is this still too high?

> Use CMake fetchContent instead of git submodules for external dependencies, which is more flexible.

I'll take a look at fetchContent.

**Comment by thatname** [comment]
> I will add target `FlyCube` that contains implementation for all graphics backends. Is this what you offer?
I mean one target for one backend. If there is a D3D12 DLL and a Vulkan DLL, An app can choose to load only one on start, thus consume less RAM.
> 3.28 was required to link with MoltenVK.xcframework. I ended up replacing the version with 3.22 in [bd18fbd](https://github.com/andrejnau/FlyCube/commit/bd18fbd1b8cffbe88b12fd42f07a93eea9d40374) . Is this still too high?
3.22 is OK. For Ubuntu v22.04 LTS, current version of CMake package from offical source is 3.22.1-1.

**Comment by andrejnau** [comment]
> * Make VKResource and MTLResource abstract, move implementation to image/buffer/sampler/accel subclasses. After change:
>   
>   * Resource subclasses cost less memory.
>   * Most branching logic can be removed, because all methods of Resource are virtual.

This is a good idea, done in https://github.com/andrejnau/FlyCube/commit/5f71753635ba6140104f2dc453c927ba3158c1ad

> * Add CopyTextureToBuffer(), which is useful.

Done in https://github.com/andrejnau/FlyCube/commit/379d8a12cbb3b1ff812f2246d0129ba53dcba490 + https://github.com/andrejnau/FlyCube/commit/a08d349e19a757f9bc564dfc09d6760c3c4d7168

> * Make debug layer optional. For now, debug layer is always enabled when debugger attached, which is slow.

Partially done in https://github.com/andrejnau/FlyCube/commit/6e049b321cc2320732bc6e437d4e57799b0096b3, I added `ENABLE_VALIDATION` cmake option, but it is still enabled by default.

> * Add depth range parameter for SetViewport().

Done in https://github.com/andrejnau/FlyCube/commit/34e354bc73e810de084dbb83823c56a101138502

> * Remove glm from acceleration structure dependency, user may prefer other math library.

User may use any math library, not sure that copy to float[3][4] is easier then copy to glm::mat3x4. But I agree that it is better not to use glm in the interface, done in https://github.com/andrejnau/FlyCube/commit/263da38afbe982c873ebd4f3fadbe572e96b288a + https://github.com/andrejnau/FlyCube/commit/d41b4322aabc74316dcfbe8cfebffb9aea44294c

However, FlyCube is still dependent on glm because of gli.

**Comment by andrejnau** [comment]
> * Use CMake fetchContent instead of git submodules for external dependencies, which is more flexible.

FetchContent certainly has some advantages, but it also has some problems.
1) Much slower configuration time, since dependencies are fetched during CMake configure step. I often need to have several build versions with different options, and sometimes due to various problems I have to delete build dir and start over again. It can be fixed by using a shared FetchContent cache between different builds, but it's difficult to implement correctly.
2) No visibility of changes in git, making it harder to track or patch dependency code.
